version: '3.1'

services:
  db:
    image: postgres:15.1
    privileged: true
    restart: always
    ports:
      - 6432:6432
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: db
  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
