# Generated by Django 3.2.8 on 2022-10-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='users',
            field=models.ForeignKey(blank=True, help_text='поля авто заметки', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
